### ISSUE TITLE
Unnecessarily write to EEPROM

### ISSUE THREAD

**Issue by corvusnix** [ZioGuido/Crumar_D9U#1]
Each time the device is started, the same value that has just been read is unneecessarily written into the EEPROM. The EEPROM memory has a specified lifetime of 100,000 write/erase cycles, so any unnecessary write command should be avoided. To fix this, `EEPROM.write(0x01, mode);` should be replaced by `EEPROM.update(0x01, mode);` in the function `set_mode()`.
Check out [Arduino Reference - EEPROMUpdate](https://www.arduino.cc/en/Reference/EEPROMUpdate) for details.

**Comment by jlearman** [comment]
Good point, though I doubt I'd turn mine on more than 10,000 times. ;-)

**Comment by ZioGuido** [comment]
If you turn it on once a day, every day, for 100K cycles it's 273 years. 
I promise I will replace your Arduino when it stops writing to EEPROM in 2295.

**Comment by corvusnix** [comment]
I'm sorry to review your code and talk about the bad programming practices
I encountered. It won't happen again, I promise.

Mark Miles ***@***.***> schrieb am Di., 1. Nov. 2022, 19:13:

**Comment by ZioGuido** [comment]
Ehm... That was just a joke...


Il Mar 1 Nov 2022, 20:36 corvusnix ***@***.***> ha scritto:

**Comment by corvusnix** [comment]
Sorry, I didn't mean to be rude.
A weak power supply, for example, can trigger many resets in a short time.
This will wear out the EEPROM much faster than this optimistic calculation
assumes. There is no reason to let something like this break the device,
especially if it can be avoided. If there's one thing I've learned from
working with microcontrollers, it's that there are more pitfalls than a
developer can imagine.

Have a nice day

**Comment by jlearman** [comment]
Sorry also, I didn't mean to be rude either.  The issue is valid, IMHO.
